name:                apns-http2
version:             0.1.1.0
synopsis:            Apple Push Notification service HTTP/2 integration.
homepage:            https://github.com/ConferOpenSource/apns-http2#readme
license:             BSD3
license-file:        LICENSE
author:              Confer Health, Inc.
maintainer:          oss@vitalbio.com
copyright:           2017 Confer Health, Inc., 2020 Vital Biosciences
category:            Network

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - async
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - data-default
  - http2
  - keys
  - lens
  - lifted-base
  - mmorph
  - mtl
  - network
  - stm
  - stm-chans
  - stm-conduit
  - text
  - time
  - tls
  - x509
  - x509-store
  - x509-validation

ghc-options: -Wall -O2

library:
  source-dirs: src

executables:
  apns-http2-example:
    source-dirs:      example
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - aeson-qq
      - apns-http2
      - base16-bytestring
      - x509-system
